use std::mem;

use egui::{Context, Event, Key, Modifiers, Rect, Vec2};
use horizon_core::{ShortcutModifiers, WorkspaceId};

use super::super::super::input::{TerminalInputEvent, terminal_input_events};
use super::super::shortcuts::shortcut_pressed;
use super::super::{CanvasPanSpaceKeyState, HorizonApp};

impl CanvasPanSpaceKeyState {
    /// Filter terminal events for a single hold-to-pan key (Space or Tab).
    ///
    /// While the key is held and a pan claims it, the key press (plus any
    /// key-repeat, generated text and the eventual release) is dropped so the
    /// terminal never sees it. If the key is released without a pan ever
    /// claiming it (a plain tap), the buffered events are flushed back so the
    /// terminal still receives the keystroke (e.g. shell tab-completion).
    ///
    /// `key` selects which key this state machine governs; `pan_claimed` is the
    /// per-frame "this gesture is panning" flag for that key. Each held key gets
    /// its own [`CanvasPanSpaceKeyState`] instance, so Space and Tab are tracked
    /// independently and one filter is applied after the other.
    fn filter_terminal_events(
        &mut self,
        events: &[TerminalInputEvent],
        key: Key,
        pan_claimed: bool,
    ) -> Vec<TerminalInputEvent> {
        let mut filtered = Vec::with_capacity(events.len());

        if pan_claimed && matches!(self, Self::Pending(_)) {
            *self = Self::Consumed;
        }

        for event in events {
            if self.handle_pan_key_event(event, key, pan_claimed, &mut filtered) {
                continue;
            }

            if matches!(self, Self::Pending(_)) {
                filtered.extend(self.flush_pending());
            }

            filtered.push(event.clone());
        }

        filtered
    }

    fn handle_pan_key_event(
        &mut self,
        event: &TerminalInputEvent,
        key: Key,
        pan_claimed: bool,
        filtered: &mut Vec<TerminalInputEvent>,
    ) -> bool {
        match self {
            Self::Idle => {
                if is_pan_key_start_event(&event.event, key) {
                    if pan_claimed {
                        *self = Self::Consumed;
                    } else {
                        *self = Self::Pending(vec![event.clone()]);
                    }
                    return true;
                }
            }
            Self::Pending(pending) => {
                if is_pan_key_related_event(&event.event, key) {
                    pending.push(event.clone());
                    if pan_claimed {
                        *self = Self::Consumed;
                    } else if is_pan_key_release(&event.event, key) {
                        filtered.extend(self.flush_pending());
                    }
                    return true;
                }
            }
            Self::Consumed => {
                if is_pan_key_related_event(&event.event, key) {
                    if is_pan_key_release(&event.event, key) {
                        *self = Self::Idle;
                    }
                    return true;
                }
            }
        }

        false
    }

    fn flush_pending(&mut self) -> Vec<TerminalInputEvent> {
        match mem::take(self) {
            Self::Pending(events) => events,
            state => {
                *self = state;
                Vec::new()
            }
        }
    }
}

/// Text generated by a hold-to-pan key, used to recognise the key's text
/// counterpart (`" "` for Space, `"\t"` for Tab) so it can be deferred too.
fn pan_key_text(key: Key) -> Option<&'static str> {
    match key {
        Key::Space => Some(" "),
        Key::Tab => Some("\t"),
        _ => None,
    }
}

fn is_pan_key_start_event(event: &Event, key: Key) -> bool {
    matches!(
        event,
        Event::Key {
            key: event_key,
            pressed: true,
            repeat: false,
            modifiers,
            ..
        } if *event_key == key && space_drag_modifier_active(*modifiers)
    )
}

fn is_pan_key_related_event(event: &Event, key: Key) -> bool {
    if matches!(event, Event::Key { key: event_key, .. } if *event_key == key) {
        return true;
    }
    match pan_key_text(key) {
        Some(expected) => {
            matches!(event, Event::Text(text) | Event::Ime(egui::ImeEvent::Commit(text)) if text == expected)
        }
        None => false,
    }
}

fn is_pan_key_release(event: &Event, key: Key) -> bool {
    matches!(
        event,
        Event::Key {
            key: event_key,
            pressed: false,
            ..
        } if *event_key == key
    )
}

fn space_drag_modifier_active(modifiers: Modifiers) -> bool {
    !modifiers.ctrl && !modifiers.command && !modifiers.alt
}

/// "Hold-to-pan with the touchpad": while the user HOLDS Space, a 2-finger /
/// wheel scroll pans the canvas anywhere inside it (including over a terminal
/// panel). This is the scroll counterpart of Space+left-drag panning. It is
/// gated off when Ctrl/Cmd is held (that gesture is reserved for zoom) and only
/// active when a scroll actually happened this frame.
fn space_scroll_pan_active(space_down: bool, pointer_in_canvas: bool, scroll: Vec2, ctrl_or_cmd: bool) -> bool {
    space_down && pointer_in_canvas && scroll != Vec2::ZERO && !ctrl_or_cmd
}

/// Hold-to-pan with Tab: identical to [`space_scroll_pan_active`] but driven by
/// the Tab key. On X11 keyboard modifiers (Alt) are not delivered to the app
/// over a terminal, but regular keys tracked via `input.key_down` are, so Tab
/// is a reliable hold-to-pan key even when the pointer is over a terminal
/// panel. While Tab drives a pan the Tab keystroke is deferred from the
/// terminal (see [`CanvasPanSpaceKeyState`]); a plain Tab tap (no scroll) is not
/// claimed and still reaches the terminal for shell tab-completion.
fn tab_scroll_pan_active(tab_down: bool, pointer_in_canvas: bool, scroll: Vec2, ctrl_or_cmd: bool) -> bool {
    tab_down && pointer_in_canvas && scroll != Vec2::ZERO && !ctrl_or_cmd
}

/// Pick the modifier set to use for the scroll-over-panel pan-modifier
/// (e.g. Alt) decision. On X11 a touchpad scroll event carries no
/// keyboard-modifier state, so during a scroll `current` reports the pan
/// modifier as released even when physically held. To work around this we use
/// `latched` (captured from the most recent non-scroll frame) while a scroll is
/// present, and `current` otherwise. This only affects the pan-modifier
/// membership test; per-frame, key-driven modifier logic keeps using the raw
/// modifiers.
fn effective_scroll_modifiers(current: Modifiers, latched: Modifiers, scrolling: bool) -> Modifiers {
    if scrolling { latched } else { current }
}

/// Convert the currently held egui [`Modifiers`] into the
/// [`ShortcutModifiers`] bitset used by the pan-modifier config so that
/// [`horizon_core::scroll_should_pan_canvas`] can test membership. `command`
/// is the platform-primary modifier and is mapped to both `PRIMARY` and the
/// concrete `CTRL`/`MAC_CMD` bits so a `pan_modifier` of `Ctrl` (which resolves
/// to `PRIMARY`) or `Control`/`Cmd` all match what the user actually pressed.
fn held_shortcut_modifiers(modifiers: Modifiers) -> ShortcutModifiers {
    let mut held = ShortcutModifiers::NONE;
    if modifiers.alt {
        held.insert(ShortcutModifiers::ALT);
    }
    if modifiers.shift {
        held.insert(ShortcutModifiers::SHIFT);
    }
    if modifiers.ctrl {
        held.insert(ShortcutModifiers::CTRL);
    }
    if modifiers.mac_cmd {
        held.insert(ShortcutModifiers::MAC_CMD);
    }
    if modifiers.command {
        held.insert(ShortcutModifiers::PRIMARY);
        held.insert(if cfg!(target_os = "macos") {
            ShortcutModifiers::MAC_CMD
        } else {
            ShortcutModifiers::CTRL
        });
    }
    held
}

impl HorizonApp {
    pub(in super::super) fn handle_fullscreen_toggle(&mut self, ctx: &Context) {
        let (panel_toggle, window_toggle, exit_fullscreen) = ctx.input(|input| {
            (
                shortcut_pressed(input, self.shortcuts.fullscreen_panel),
                shortcut_pressed(input, self.shortcuts.fullscreen_window),
                shortcut_pressed(input, self.shortcuts.exit_fullscreen_panel),
            )
        });

        if window_toggle {
            let is_fullscreen = ctx.input(|input| input.viewport().fullscreen.unwrap_or(false));
            ctx.send_viewport_cmd(egui::ViewportCommand::Fullscreen(!is_fullscreen));
        } else if panel_toggle {
            self.fullscreen_panel = if self.fullscreen_panel.is_some() {
                None
            } else {
                self.board.focused
            };
        } else if exit_fullscreen && self.fullscreen_panel.is_some() {
            self.fullscreen_panel = None;
        }

        if let Some(panel_id) = self.fullscreen_panel
            && self.board.panel(panel_id).is_none()
        {
            self.fullscreen_panel = None;
        }
    }

    #[profiling::function]
    pub(in super::super) fn handle_canvas_pan(&mut self, ctx: &Context) {
        self.handle_canvas_pan_in_rect(ctx, self.canvas_rect(ctx), None);
    }

    #[profiling::function]
    pub(in super::super) fn handle_canvas_pan_in_rect(
        &mut self,
        ctx: &Context,
        canvas_rect: Rect,
        visible_workspace: Option<WorkspaceId>,
    ) {
        let (
            events,
            pointer_position,
            middle_down,
            primary_down,
            space_down,
            tab_down,
            modifiers,
            scroll,
            pointer_delta,
            zoom_delta,
        ) = ctx.input(|input| {
            (
                input.events.clone(),
                input.pointer.interact_pos().or_else(|| input.pointer.hover_pos()),
                input.pointer.middle_down(),
                input.pointer.primary_down(),
                input.key_down(egui::Key::Space),
                input.key_down(egui::Key::Tab),
                input.modifiers,
                input.smooth_scroll_delta + input.raw_scroll_delta,
                input.pointer.delta(),
                input.zoom_delta(),
            )
        });
        let panel_geometry = self.visible_panel_geometry_for_canvas_view(canvas_rect, visible_workspace);
        let pointer_in_canvas = pointer_position.is_some_and(|position| canvas_rect.contains(position));
        let space_drag_claimed =
            pointer_in_canvas && primary_down && space_down && space_drag_modifier_active(modifiers);
        let ctrl_or_cmd = modifiers.ctrl || modifiers.command;
        // X11 touchpad scroll events carry no modifier state, so latch the
        // modifiers from non-scroll frames and reuse them for the pan-modifier
        // decision during a scroll. Only the pan-modifier membership test below
        // uses `effective_modifiers`; everything else stays on raw `modifiers`.
        let scrolling = scroll != Vec2::ZERO;
        if !scrolling {
            self.latched_scroll_modifiers = modifiers;
        }
        let effective_modifiers = effective_scroll_modifiers(modifiers, self.latched_scroll_modifiers, scrolling);
        // Space held + a scroll gesture pans the canvas even over a panel; the
        // Space key must be deferred from the terminal exactly like Space+drag.
        let space_scroll_pan_active = space_scroll_pan_active(space_down, pointer_in_canvas, scroll, ctrl_or_cmd);
        // Tab held + a scroll gesture pans the canvas even over a panel; the Tab
        // key must be deferred from the terminal so a held-Tab pan never spams
        // shell tab-completion. A plain Tab tap is not claimed and still reaches
        // the terminal.
        let tab_scroll_pan_active = tab_scroll_pan_active(tab_down, pointer_in_canvas, scroll, ctrl_or_cmd);
        let pointer_over_terminal_body = primary_selection_routing_active()
            && pointer_position.is_some_and(|position| {
                panel_geometry
                    .iter()
                    .filter_map(|(_, geometry)| geometry.terminal_body_screen_rect)
                    .any(|rect| rect.contains(position))
            });
        let terminal_events = self.terminal_events_for_viewport(ctx.viewport_id(), &events);
        // Delay plain Space forwarding until we know whether the key becomes
        // the canvas-pan modifier or an actual terminal keystroke.
        let space_filtered = self.pending_space_pan_key.filter_terminal_events(
            &terminal_events,
            egui::Key::Space,
            space_drag_claimed || space_scroll_pan_active,
        );
        self.terminal_keyboard_events =
            self.pending_tab_pan_key
                .filter_terminal_events(&space_filtered, egui::Key::Tab, tab_scroll_pan_active);
        let target = if !pointer_in_canvas {
            MiddlePanTarget::OutsideCanvas
        } else if pointer_over_terminal_body {
            MiddlePanTarget::TerminalBody
        } else {
            MiddlePanTarget::EmptyCanvas
        };
        let mode = if ctrl_or_cmd {
            MiddlePanMode::Forced
        } else {
            MiddlePanMode::Default
        };
        self.middle_pan_active =
            next_middle_pan_active(self.middle_pan_active, middle_down, target, mode, pointer_delta);
        self.canvas_pan_input_claimed = pointer_in_canvas && (self.middle_pan_active || space_drag_claimed);
        if pointer_in_canvas && (zoom_delta - 1.0).abs() > f32::EPSILON {
            let anchor = pointer_position.unwrap_or_else(|| canvas_rect.center());
            if self.zoom_canvas_at(canvas_rect, anchor, self.canvas_view.zoom * zoom_delta) {
                self.clear_terminal_selections();
            }
            self.canvas_pan_input_claimed = false;
            self.is_panning = false;
            return;
        }

        let drag_panning = self.canvas_pan_input_claimed;
        let pointer_over_panel = pointer_position.is_some_and(|position| {
            pointer_in_canvas
                && !drag_panning
                && scroll != Vec2::ZERO
                && !ctrl_or_cmd
                && panel_geometry
                    .iter()
                    .any(|(_, geometry)| geometry.screen_rect.contains(position))
        });
        // Story 4: when a scroll lands on a panel and the configured pan
        // modifier is held (or the toggle is on), pan the board instead of
        // letting the panel consume the scroll. Only evaluated when a scroll is
        // actually over a panel, so the input hot path stays cheap.
        let scroll_pans_over_panel = pointer_over_panel
            && (horizon_core::scroll_should_pan_canvas(
                held_shortcut_modifiers(effective_modifiers),
                self.resolved_pan_modifier,
                self.scroll_pans_over_panels,
            ) || space_scroll_pan_active
                || tab_scroll_pan_active);
        if scroll_pans_over_panel {
            // Drop the wheel events so the terminal widget (rendered later this
            // frame) does not also scroll the same gesture.
            ctx.input_mut(|input| input.events.retain(|event| !matches!(event, Event::MouseWheel { .. })));
        }
        let pointer_over_panel = pointer_over_panel && !scroll_pans_over_panel;
        let pan_delta = if drag_panning {
            pointer_delta
        } else if pointer_in_canvas && !pointer_over_panel && !ctrl_or_cmd {
            if modifiers.shift && scroll.x == 0.0 {
                Vec2::new(scroll.y, 0.0)
            } else {
                scroll
            }
        } else {
            Vec2::ZERO
        };

        self.is_panning = pan_delta != Vec2::ZERO;
        if self.is_panning {
            self.pan_target = None;
            let mut pan_offset = Vec2::new(self.canvas_view.pan_offset[0], self.canvas_view.pan_offset[1]);
            pan_offset += pan_delta;
            self.canvas_view.set_pan_offset([pan_offset.x, pan_offset.y]);
            self.mark_runtime_dirty();
            self.clear_terminal_selections();
        }
    }

    fn clear_terminal_selections(&self) {
        for panel in &self.board.panels {
            if let Some(terminal) = panel.terminal() {
                terminal.clear_selection();
            }
        }
    }

    fn terminal_events_for_viewport(
        &mut self,
        viewport_id: egui::ViewportId,
        events: &[Event],
    ) -> Vec<TerminalInputEvent> {
        let frame_keyboard_events = self.frame_keyboard_events.remove(&viewport_id).unwrap_or_default();
        terminal_input_events(events, frame_keyboard_events)
    }
}

#[derive(Clone, Copy)]
enum MiddlePanTarget {
    OutsideCanvas,
    EmptyCanvas,
    TerminalBody,
}

#[derive(Clone, Copy)]
enum MiddlePanMode {
    Default,
    Forced,
}

fn next_middle_pan_active(
    was_active: bool,
    middle_down: bool,
    target: MiddlePanTarget,
    mode: MiddlePanMode,
    pointer_delta: Vec2,
) -> bool {
    if !middle_down {
        return false;
    }

    if was_active {
        return true;
    }

    if pointer_delta == Vec2::ZERO {
        return false;
    }

    match (target, mode) {
        (MiddlePanTarget::OutsideCanvas, _) | (MiddlePanTarget::TerminalBody, MiddlePanMode::Default) => false,
        (MiddlePanTarget::EmptyCanvas, _) | (MiddlePanTarget::TerminalBody, MiddlePanMode::Forced) => true,
    }
}

fn primary_selection_routing_active() -> bool {
    cfg!(target_os = "linux")
}

#[cfg(test)]
mod tests {
    use egui::{Event, Key, Modifiers, Vec2};

    use super::super::super::super::input::TerminalInputEvent;
    use super::super::super::CanvasPanSpaceKeyState;
    use super::{
        MiddlePanMode, MiddlePanTarget, effective_scroll_modifiers, next_middle_pan_active,
        primary_selection_routing_active, space_scroll_pan_active, tab_scroll_pan_active,
    };

    #[test]
    fn effective_scroll_modifiers_uses_current_when_not_scrolling() {
        let current = Modifiers {
            alt: true,
            ..Modifiers::default()
        };
        let latched = Modifiers::default();
        assert_eq!(effective_scroll_modifiers(current, latched, false), current);
    }

    #[test]
    fn effective_scroll_modifiers_uses_latched_when_scrolling() {
        let current = Modifiers::default();
        let latched = Modifiers {
            alt: true,
            ..Modifiers::default()
        };
        assert_eq!(effective_scroll_modifiers(current, latched, true), latched);
    }

    #[test]
    fn effective_scroll_modifiers_recovers_x11_alt_during_scroll() {
        // X11 fix: Alt was held (latched alt=true) on the prior non-scroll
        // frame, but the touchpad scroll event reports alt=false. The effective
        // modifiers must still see Alt so scroll-over-panel panning triggers.
        let current = Modifiers {
            alt: false,
            ..Modifiers::default()
        };
        let latched = Modifiers {
            alt: true,
            ..Modifiers::default()
        };
        assert!(effective_scroll_modifiers(current, latched, true).alt);
    }

    #[test]
    fn space_scroll_pan_active_when_space_held_and_scrolling_in_canvas() {
        assert!(space_scroll_pan_active(true, true, Vec2::new(0.0, 12.0), false));
        assert!(space_scroll_pan_active(true, true, Vec2::new(8.0, 0.0), false));
    }

    #[test]
    fn space_scroll_pan_inactive_without_space_or_scroll_or_canvas() {
        // Space not held.
        assert!(!space_scroll_pan_active(false, true, Vec2::new(0.0, 12.0), false));
        // No scroll this frame (plain Space tap).
        assert!(!space_scroll_pan_active(true, true, Vec2::ZERO, false));
        // Pointer outside the canvas.
        assert!(!space_scroll_pan_active(true, false, Vec2::new(0.0, 12.0), false));
    }

    #[test]
    fn space_scroll_pan_inactive_when_ctrl_or_cmd_held() {
        // Ctrl/Cmd is reserved for zoom, not space-scroll panning.
        assert!(!space_scroll_pan_active(true, true, Vec2::new(0.0, 12.0), true));
    }

    #[test]
    fn space_candidate_is_dropped_once_scroll_pan_claims_it() {
        // A Space press arrives, then a scroll lands while Space is still held:
        // the claim (here passed as the combined `space_drag_claimed ||
        // space_scroll_pan_active` flag) must suppress the Space keystroke.
        let mut state = CanvasPanSpaceKeyState::default();

        assert!(
            state
                .filter_terminal_events(
                    &[
                        terminal_event(space_press()),
                        terminal_event(Event::Text(" ".to_owned()))
                    ],
                    Key::Space,
                    false
                )
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Pending(_)));

        // Scroll-pan claims the Space: nothing is forwarded to the terminal.
        assert!(state.filter_terminal_events(&[], Key::Space, true).is_empty());
        assert!(matches!(state, CanvasPanSpaceKeyState::Consumed));

        assert!(
            state
                .filter_terminal_events(&[terminal_event(space_release())], Key::Space, false)
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn plain_space_is_delayed_until_release() {
        let mut state = CanvasPanSpaceKeyState::default();
        let press = space_press();
        let text = Event::Text(" ".to_owned());
        let release = space_release();

        assert!(
            state
                .filter_terminal_events(
                    &[terminal_event(press.clone()), terminal_event(text.clone())],
                    Key::Space,
                    false
                )
                .is_empty()
        );

        let filtered = state.filter_terminal_events(&[terminal_event(release.clone())], Key::Space, false);
        assert_eq!(
            filtered,
            vec![terminal_event(press), terminal_event(text), terminal_event(release)]
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn space_candidate_is_dropped_once_drag_pan_claims_it() {
        let mut state = CanvasPanSpaceKeyState::default();

        assert!(
            state
                .filter_terminal_events(
                    &[
                        terminal_event(space_press()),
                        terminal_event(Event::Text(" ".to_owned()))
                    ],
                    Key::Space,
                    false
                )
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Pending(_)));

        assert!(state.filter_terminal_events(&[], Key::Space, true).is_empty());
        assert!(matches!(state, CanvasPanSpaceKeyState::Consumed));

        assert!(
            state
                .filter_terminal_events(&[terminal_event(space_release())], Key::Space, false)
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn pending_space_flushes_before_later_non_space_input() {
        let mut state = CanvasPanSpaceKeyState::default();
        let press = space_press();
        let text = Event::Text(" ".to_owned());
        let letter = Event::Key {
            key: Key::A,
            physical_key: Some(Key::A),
            pressed: true,
            repeat: false,
            modifiers: Modifiers::NONE,
        };

        assert!(
            state
                .filter_terminal_events(
                    &[terminal_event(press.clone()), terminal_event(text.clone())],
                    Key::Space,
                    false
                )
                .is_empty()
        );

        let filtered = state.filter_terminal_events(&[terminal_event(letter.clone())], Key::Space, false);
        assert_eq!(
            filtered,
            vec![terminal_event(press), terminal_event(text), terminal_event(letter)]
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn tab_scroll_pan_active_when_tab_held_and_scrolling_in_canvas() {
        assert!(tab_scroll_pan_active(true, true, Vec2::new(0.0, 12.0), false));
        assert!(tab_scroll_pan_active(true, true, Vec2::new(8.0, 0.0), false));
    }

    #[test]
    fn tab_scroll_pan_inactive_without_tab_or_scroll_or_canvas() {
        // Tab not held.
        assert!(!tab_scroll_pan_active(false, true, Vec2::new(0.0, 12.0), false));
        // No scroll this frame (plain Tab tap).
        assert!(!tab_scroll_pan_active(true, true, Vec2::ZERO, false));
        // Pointer outside the canvas.
        assert!(!tab_scroll_pan_active(true, false, Vec2::new(0.0, 12.0), false));
    }

    #[test]
    fn tab_scroll_pan_inactive_when_ctrl_or_cmd_held() {
        // Ctrl/Cmd is reserved for zoom, not tab-scroll panning.
        assert!(!tab_scroll_pan_active(true, true, Vec2::new(0.0, 12.0), true));
    }

    #[test]
    fn tab_candidate_is_dropped_once_scroll_pan_claims_it() {
        // A Tab press arrives, then a scroll lands while Tab is still held: the
        // tab-scroll-pan claim must suppress the Tab keystroke so the terminal
        // never receives a tab (no autocomplete spam during a pan).
        let mut state = CanvasPanSpaceKeyState::default();

        assert!(
            state
                .filter_terminal_events(
                    &[
                        terminal_event(tab_press()),
                        terminal_event(Event::Text("\t".to_owned()))
                    ],
                    Key::Tab,
                    false
                )
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Pending(_)));

        // Scroll-pan claims the Tab: nothing is forwarded to the terminal,
        // including the key-repeat that arrives while Tab stays held.
        assert!(
            state
                .filter_terminal_events(&[terminal_event(tab_repeat())], Key::Tab, true)
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Consumed));

        assert!(
            state
                .filter_terminal_events(&[terminal_event(tab_release())], Key::Tab, false)
                .is_empty()
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn plain_tab_tap_is_delivered_on_release() {
        // A Tab tap with no scroll is never claimed, so the buffered Tab events
        // are flushed back on release and the terminal still gets the tab
        // (shell autocomplete preserved).
        let mut state = CanvasPanSpaceKeyState::default();
        let press = tab_press();
        let text = Event::Text("\t".to_owned());
        let release = tab_release();

        assert!(
            state
                .filter_terminal_events(
                    &[terminal_event(press.clone()), terminal_event(text.clone())],
                    Key::Tab,
                    false
                )
                .is_empty()
        );

        let filtered = state.filter_terminal_events(&[terminal_event(release.clone())], Key::Tab, false);
        assert_eq!(
            filtered,
            vec![terminal_event(press), terminal_event(text), terminal_event(release)]
        );
        assert!(matches!(state, CanvasPanSpaceKeyState::Idle));
    }

    #[test]
    fn middle_pan_starts_on_empty_canvas() {
        assert!(next_middle_pan_active(
            false,
            true,
            MiddlePanTarget::EmptyCanvas,
            MiddlePanMode::Default,
            Vec2::new(4.0, 0.0)
        ));
    }

    #[test]
    fn middle_pan_does_not_start_on_terminal_body_without_modifier() {
        assert!(!next_middle_pan_active(
            false,
            true,
            MiddlePanTarget::TerminalBody,
            MiddlePanMode::Default,
            Vec2::new(4.0, 0.0)
        ));
    }

    #[test]
    fn middle_pan_overrides_terminal_body_with_ctrl_or_cmd() {
        assert!(next_middle_pan_active(
            false,
            true,
            MiddlePanTarget::TerminalBody,
            MiddlePanMode::Forced,
            Vec2::new(4.0, 0.0)
        ));
    }

    #[test]
    fn middle_pan_stays_active_until_button_release() {
        assert!(next_middle_pan_active(
            true,
            true,
            MiddlePanTarget::OutsideCanvas,
            MiddlePanMode::Default,
            Vec2::ZERO
        ));
        assert!(!next_middle_pan_active(
            true,
            false,
            MiddlePanTarget::EmptyCanvas,
            MiddlePanMode::Default,
            Vec2::ZERO
        ));
    }

    #[test]
    fn middle_pan_waits_for_motion_before_claiming_press() {
        assert!(!next_middle_pan_active(
            false,
            true,
            MiddlePanTarget::EmptyCanvas,
            MiddlePanMode::Default,
            Vec2::ZERO
        ));
    }

    #[test]
    fn primary_selection_routing_matches_linux_only_behavior() {
        assert_eq!(primary_selection_routing_active(), cfg!(target_os = "linux"));
    }

    fn terminal_event(event: Event) -> TerminalInputEvent {
        TerminalInputEvent {
            event,
            key_without_modifiers_text: None,
            observed_key: None,
        }
    }

    fn space_press() -> Event {
        Event::Key {
            key: Key::Space,
            physical_key: Some(Key::Space),
            pressed: true,
            repeat: false,
            modifiers: Modifiers::NONE,
        }
    }

    fn space_release() -> Event {
        Event::Key {
            key: Key::Space,
            physical_key: Some(Key::Space),
            pressed: false,
            repeat: false,
            modifiers: Modifiers::NONE,
        }
    }

    fn tab_press() -> Event {
        Event::Key {
            key: Key::Tab,
            physical_key: Some(Key::Tab),
            pressed: true,
            repeat: false,
            modifiers: Modifiers::NONE,
        }
    }

    fn tab_repeat() -> Event {
        Event::Key {
            key: Key::Tab,
            physical_key: Some(Key::Tab),
            pressed: true,
            repeat: true,
            modifiers: Modifiers::NONE,
        }
    }

    fn tab_release() -> Event {
        Event::Key {
            key: Key::Tab,
            physical_key: Some(Key::Tab),
            pressed: false,
            repeat: false,
            modifiers: Modifiers::NONE,
        }
    }
}
